#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Play_Brix.Resource", IsApplication=true)]

namespace Play_Brix
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ChessAPI.Resource.String.ApplicationName = global::Play_Brix.Resource.String.ApplicationName;
			global::ChessAPI.Resource.String.Hello = global::Play_Brix.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bluebishop = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blueking = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blueknight = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bluepawn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bluequeen = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bluerook = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int obey = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int yellowbishop = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int yellowking = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int yellowknight = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int yellowpawn = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int yellowqueen = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int yellowrook = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int ImageButton1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int ImageButton1n = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int a8 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ai7 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int imageImageButton1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int textView1 = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
