#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Play_Brix.Resource", IsApplication=true)]

namespace Play_Brix
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ChessAPI.Resource.String.ApplicationName = global::Play_Brix.Resource.String.ApplicationName;
			global::ChessAPI.Resource.String.Hello = global::Play_Brix.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bluebishop = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blueking = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blueknight = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bluepawn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bluequeen = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bluerook = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Error = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int point = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Transparent = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int yellowbishop = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int yellowking = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int yellowknight = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int yellowpawn = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int yellowqueen = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int yellowrook = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050039
			public const int a1 = 2131034169;
			
			// aapt resource value: 0x7f050031
			public const int a2 = 2131034161;
			
			// aapt resource value: 0x7f050029
			public const int a3 = 2131034153;
			
			// aapt resource value: 0x7f050021
			public const int a4 = 2131034145;
			
			// aapt resource value: 0x7f050019
			public const int a5 = 2131034137;
			
			// aapt resource value: 0x7f050011
			public const int a6 = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int a7 = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int a8 = 2131034113;
			
			// aapt resource value: 0x7f05003a
			public const int b1 = 2131034170;
			
			// aapt resource value: 0x7f050032
			public const int b2 = 2131034162;
			
			// aapt resource value: 0x7f05002a
			public const int b3 = 2131034154;
			
			// aapt resource value: 0x7f050022
			public const int b4 = 2131034146;
			
			// aapt resource value: 0x7f05001a
			public const int b5 = 2131034138;
			
			// aapt resource value: 0x7f050012
			public const int b6 = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int b7 = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int b8 = 2131034114;
			
			// aapt resource value: 0x7f05003b
			public const int c1 = 2131034171;
			
			// aapt resource value: 0x7f050033
			public const int c2 = 2131034163;
			
			// aapt resource value: 0x7f05002b
			public const int c3 = 2131034155;
			
			// aapt resource value: 0x7f050023
			public const int c4 = 2131034147;
			
			// aapt resource value: 0x7f05001b
			public const int c5 = 2131034139;
			
			// aapt resource value: 0x7f050013
			public const int c6 = 2131034131;
			
			// aapt resource value: 0x7f05000b
			public const int c7 = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int c8 = 2131034115;
			
			// aapt resource value: 0x7f05003c
			public const int d1 = 2131034172;
			
			// aapt resource value: 0x7f050034
			public const int d2 = 2131034164;
			
			// aapt resource value: 0x7f05002c
			public const int d3 = 2131034156;
			
			// aapt resource value: 0x7f050024
			public const int d4 = 2131034148;
			
			// aapt resource value: 0x7f05001c
			public const int d5 = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int d6 = 2131034132;
			
			// aapt resource value: 0x7f05000c
			public const int d7 = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int d8 = 2131034116;
			
			// aapt resource value: 0x7f05003d
			public const int e1 = 2131034173;
			
			// aapt resource value: 0x7f050035
			public const int e2 = 2131034165;
			
			// aapt resource value: 0x7f05002d
			public const int e3 = 2131034157;
			
			// aapt resource value: 0x7f050025
			public const int e4 = 2131034149;
			
			// aapt resource value: 0x7f05001d
			public const int e5 = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int e6 = 2131034133;
			
			// aapt resource value: 0x7f05000d
			public const int e7 = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int e8 = 2131034117;
			
			// aapt resource value: 0x7f05003e
			public const int f1 = 2131034174;
			
			// aapt resource value: 0x7f050036
			public const int f2 = 2131034166;
			
			// aapt resource value: 0x7f05002e
			public const int f3 = 2131034158;
			
			// aapt resource value: 0x7f050026
			public const int f4 = 2131034150;
			
			// aapt resource value: 0x7f05001e
			public const int f5 = 2131034142;
			
			// aapt resource value: 0x7f050016
			public const int f6 = 2131034134;
			
			// aapt resource value: 0x7f05000e
			public const int f7 = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int f8 = 2131034118;
			
			// aapt resource value: 0x7f05003f
			public const int g1 = 2131034175;
			
			// aapt resource value: 0x7f050037
			public const int g2 = 2131034167;
			
			// aapt resource value: 0x7f05002f
			public const int g3 = 2131034159;
			
			// aapt resource value: 0x7f050027
			public const int g4 = 2131034151;
			
			// aapt resource value: 0x7f05001f
			public const int g5 = 2131034143;
			
			// aapt resource value: 0x7f050017
			public const int g6 = 2131034135;
			
			// aapt resource value: 0x7f05000f
			public const int g7 = 2131034127;
			
			// aapt resource value: 0x7f050007
			public const int g8 = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050040
			public const int h1 = 2131034176;
			
			// aapt resource value: 0x7f050038
			public const int h2 = 2131034168;
			
			// aapt resource value: 0x7f050030
			public const int h3 = 2131034160;
			
			// aapt resource value: 0x7f050028
			public const int h4 = 2131034152;
			
			// aapt resource value: 0x7f050020
			public const int h5 = 2131034144;
			
			// aapt resource value: 0x7f050018
			public const int h6 = 2131034136;
			
			// aapt resource value: 0x7f050010
			public const int h7 = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int h8 = 2131034120;
			
			// aapt resource value: 0x7f050041
			public const int imageImageButton1 = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int textView1 = 2131034178;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
